export default {
  // species actions
  FETCH_SPECIES_LOADING: 'FETCH_SPECIES_LOADING',
  FETCH_SPECIES_SUCCESS: 'FETCH_SPECIES_SUCCESS',
  FETCH_SPECIES_FAILED: 'FETCH_SPECIES_FAILED',
  FETCH_PEOPLE_LOADING: 'FETCH_PEOPLE_LOADING',
  FETCH_PEOPLE_SUCCESS: 'FETCH_PEOPLE_SUCCESS',
  FETCH_PEOPLE_FAILED: 'FETCH_PEOPLE_FAILED'
};
